---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или
    категории.
  - Пользователь должен иметь возможность фильтровать товары.
  - Пользователь должен иметь возможность добавлять товары в корзину и
    просматривать содержимое корзины.
  - Пользователь должен иметь возможность просматривать товары и просматривать
    подробную информацию о товаре.
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для
    скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт нужно протестировать на совместимость с последними версиями браузеров.
  - Сайт должен быть доступен на различных устройствах.
  - Важно, чтобы сайт мог обрабатывать большое количество трафика.
implicit:
  - Информация о товарах, ценах, скидках и акциях на сайте соответствует
    действительности и не противоречит другим разделам сайта.
  - Корректность работы системы уведомлений (о статусе заказа, о скидках и
    акциях) и возможность связи с поддержкой сайта для решения проблем.
  - Корректная работа скрытых функций, таких как добавление товаров в избранное,
    сравнение товаров, рекомендации похожих товаров и другие дополнительные
    возможности.
  - При правильном заполнении всех необходимых полей, пользователь получает
    уведомление об успешном оформлении заказа.
