---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или
    категории.
  - Пользователь должен иметь возможность фильтровать товары.
  - Пользователь должен иметь возможность добавлять товары в корзину и
    просматривать содержимое корзины.
  - Пользователь должен иметь возможность просматривать товары и просматривать
    подробную информацию о товаре.
  - На странице товара и в каталоге нужно выводить название, рейтинг, цена со скидкой и без нее.
  - На странице корзины пользователь должен иметь возможность удалять товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты. 
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для
    скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт нужно протестировать на совместимость с последними версиями браузеров.
  - Сайт должен быть доступен на различных устройствах.
  - Важно, чтобы сайт мог обрабатывать большое количество трафика.
  - Корзина должна храниться в сессии браузера.
implicit:
  - Информация о товарах, ценах, скидках и акциях на сайте соответствует
    действительности и не противоречит другим разделам сайта.
  - Сайт должен предоставлять удобную навигацию по страницам - структура сайта, логика меню, поисковой системы, фильтрации товаров. 
  - Пользователь должен иметь возможность отслеживать состояние своего заказа.
  - Пользователь должен иметь возможность сортировки и поиска товара по рейтингу.
